### ISSUE TITLE
Extraction of WiFi features from Aware data

### ISSUE THREAD

**Issue by Meng6** [carissalow/rapids#102]
Currently, RAPIDS contains three WiFi features:
- countscans: number of scanned WiFi access points during a `day_segment`, an access point can be detected multiple times over time and these appearances are counted separately
- uniquedevices: number of unique access point during a `day_segment` as identified by their `bssid`
- countscansmostuniquedevice: number of scans of the most scanned access point during a `day_segment` across the whole monitoring period

We will duplicate the above three features based on `bssid` and `ssid`.

WiFi episode features will be added in the future:
An episode is a time period during which the phone is staying connected to an access point. Statistics of the duration of connection to an access point during a `day_segment` can be calculated:

- sumdurationconnect
- maxdurationconnect
- mindurationconnect
- avgdurationconnect
- stddurationconnect

**Comment by JulioV** [comment]
Moved to https://github.com/carissalow/rapids/discussions/115
