### ISSUE TITLE
Barnett’s location features run into problems when INCLUDE_PAST_PERIODIC_SEGMENTS is set as True

### ISSUE THREAD

**Issue by OrsonXu** [carissalow/rapids#126]
**Describe the bug**
When `INCLUDE_PAST_PERIODIC_SEGMENTS` is set as True in the time segment configuration, seems like Barnett’s location features will be calculated multiple times but displayed as the same `local_segment_start_datetime` and `local_segment_start_datetime`.

**To Reproduce**
1. Set `INCLUDE_PAST_PERIODIC_SEGMENTS` as True
2. Specific periodic time segmentation setup: `daily_14dhistory,00:00:00,13D 23H 59M 59S,every_day,0`
3. Set Barnett’s location feature as True in the `config.yaml`
4. Run RAPIDS

**Expected behavior**
The first time segments will be repeated `14 times` in the `phone_locations.csv`.

**Screenshots**
![image](https://user-images.githubusercontent.com/16918237/110809618-068a7100-82c0-11eb-8d77-a9bcb00651e4.png)

**Please complete the following information:**
 - OS: Ubuntu
 - RAPIDS current commit: d8813e2
 - A link to your `config.yaml` (change the suffix to txt to upload this file)
[config_debug.txt](https://github.com/carissalow/rapids/files/6124014/config_debug.txt)
 - Type of mobile data you are dealing with: both

**Comment by JulioV** [comment]
Thank you for reporting this. I forgot to close this issue earlier, as discussed on Slack this has been fixed in v1.0 
https://github.com/carissalow/rapids/commit/d0858f88332f8f07306e500d310cadbd31bd92ef
