### ISSUE TITLE
[PHONE_CONVERSATION][PROVIDERS][RAPIDS] feature calculation bug.

### ISSUE THREAD

**Issue by yiyir** [carissalow/rapids#133]
**Describe the bug**
In [/rapids/src/features/phone_conversation/rapids/main.py line 11](https://github.com/carissalow/rapids/blob/29cc3f00e9826def890758d13726d8df0caed633/src/features/phone_conversation/rapids/main.py#L11): 
Calculation of expected total duration assumes that the length of the current time segment is 1 day (1440 minutes). 

Features related: silenceexpectedfraction, noiseexpectedfraction, voiceexpectedfraction, unknownexpectedfraction

**Expected behavior**
Should not hardcode the length of the time segment(avoid magic numbers like 1440); instead, infer from the “length” column of time_segment.csv file

**Comment by JulioV** [comment]
Thanks Yiyi, @nikunjgoel95 can you take a look at this, please?

**Comment by JulioV** [comment]
Thanks for the report @yiyir this is now fixed in 9b21196f35317872d2fa8a87efa826bdd1e5be1d
