### ISSUE TITLE
Remove moving data points before feeding into location clusterer.

### ISSUE THREAD

**Issue by yiyir** [carissalow/rapids#135]
Describe the bug
In /[rapids/src/features/phone_locations/doryab/main.py line 352](https://github.com/carissalow/rapids/blob/b3c05128fa4cb1425f13cdb395a016b537fb70d9/src/features/phone_locations/doryab/main.py#L352):
Function "mark_moving" only marked but forgot to remove moving data points before feeding data samples to clusterer.

Expected behavior
Should return df[df['stationary_or_not'] == 1]

**Comment by JulioV** [comment]
Thanks, Yiyi we are about to finish a refactor of the Doryab location provider, so I think this bug should be solved.

@Meng6 could you double-check that this is fixed?

**Comment by Meng6** [comment]
Thanks Yiyi, that bug was solved in `feature/phone_locations_doryab_refactor` branch: https://github.com/carissalow/rapids/blob/feature/phone_locations_doryab_refactor/src/features/phone_locations/doryab/doryab_clustering.py#L71.
We will release this version in the near future.

**Comment by JulioV** [comment]
Thanks @Meng6. Yes, we are waiting on our unit tests and a new home inference algorithm and then we will release the refactor

**Comment by yiyir** [comment]
@JulioV @Meng6 Great, thanks for letting me know. Looking forward to the next release!

**Comment by yiyir** [comment]
Hi @Meng6 , just want to report a potential bug in [add_doryab_extra_columns.py line 50](https://github.com/carissalow/rapids/blob/2e74f286c6ae091747f58cf62f586338dd8d3f94/src/features/phone_locations/doryab/add_doryab_extra_columns.py#L50) of branch `feature/phone_locations_doryab_refactor`:
I think the duration of stay for each location sample should be the time difference between current and next rows, instead of previous and current rows.
So line50 should be changed to: location_data["duration_in_seconds"] =  location_data.timestamp.diff().shift(-1) / 1000?

**Comment by Meng6** [comment]
Hi @yiyir , we assume the duration to be the time difference between current row and previous row. Similarly, the [distance](https://github.com/carissalow/rapids/blob/2e74f286c6ae091747f58cf62f586338dd8d3f94/src/features/phone_locations/doryab/doryab_clustering.py#L31) is also between current row and previous row. By doing so, we can get the correct `speed` related features.
The reason why we use the difference between current row and previous row instead of next row and current row is that we do not know our future data while calculating the `speed` of current row. Each row's `speed` field means the speed to arrive at current location.

**Comment by yiyir** [comment]
Hi @Meng6  I see. Yeah that makes sense for calculating speed. However, it seems that `duration_in_seconds` is later also used to calculate final features such as time at top3 clusters, location_entropy, radius_of_gyration, etc. I'm just worried that `duration_in_seconds` doesn't really reflect the duration of stay at the location associated with the data sample.

**Comment by Meng6** [comment]
I @yiyir , good questions! I think we will get the same results for the following two methods:

`method 1`: difference between next row and current row.
`method 2`: difference between current row and previous row.

Here is an example for top3 clusters features: (notes: NA of the `is_stationary` field is filled with 0)

|row_idx  |cluster_label    |duration_in_seconds (method 1)     |is_stationary (method 1)    | duration_in_seconds (method 2)     |is_stationary (method 2)    | 
|---------|---------------|--------------------------|--------|---------------------------------|-----------|
|1              |1                       |duration(row1, row2)          |1            |NA                                                  |NA (0)        |
|2              |1                       |duration(row2, row3)         |1            |duration(row1, row2)                     |1                 |
|3              |1                       |duration(row3, row4)         |0            |duration(row2, row3)                    |1                 |
|4              |2                       |duration(row4, row5)         |1            |duration(row3, row4)                    |0                 |
|5              |2                       |duration(row5, row6)         |1             |duration(row4, row5)                   |1                 |
|6              |2                       |duration(row6, row7)         |0             |duration(row5, row6)                   |1                 |
|7              |3                       |duration(row7, row8)         |1             |duration(row6, row7)                   |0                |
|8              |3                       |NA                                       |NA (0)     |duration(row7, row8)                  |1                |

Both `method 1` and `method 2`'s time at cluster 1 is duration(row1, row2) + duration(row2, row3);
time at cluster 2 is duration(row4, row5) + duration(row5, row6);
time at cluster 3 is duration(row7, row8).

Does it make sense?

**Comment by yiyir** [comment]
Hey @Meng6 , thanks for the explanation above! Yeah I agree this discussion is getting more interesting!

I just tried running Rapids with these two implementations separately, and let's compare them side by side:

<img width="1079" alt="Screen Shot 2021-05-24 at 5 43 52 PM" src="https://user-images.githubusercontent.com/31498941/119410972-a482ba80-bcb7-11eb-9e22-3b65d8dca9dc.png">

In this chunk of data, duration 73.65 was counted toward `cluster 2` with `method 1`, but not counted with `method 2`.

The final feature values are different between these two implementations as well. Take feature `timeattop2location` as an example, the difference is up to ~4 minutes for daily segments and could be more for longer time segments.

**Comment by Meng6** [comment]
Hi @yiyir , thanks for your testing. You are right, the features extracted from the above two methods are different. Different stationary rows will be included for the clustering section so that each row might be assigned a different `cluster_label` for different methods. I just updated our code to the method you mentioned (`method 1`): https://github.com/carissalow/rapids/commit/3aba52c4b8d1db58c8cd73ae9c9cbd110a949ad1
Thanks for your suggestions!

**Comment by yiyir** [comment]
@Meng6 Pleasure to help! Thanks for the good work! Closing this now.
