### ISSUE TITLE
init renv and  environment  problem

### ISSUE THREAD

**Issue by Bassel-kh** [carissalow/rapids#219]
This form is only for bug reports. For questions, feature requests, or feedback use our [Github discussions](https://github.com/carissalow/rapids/discussions)

* [* ] OS version ( Windows 10)
*when excute : conda env create -f environment.yml -n MY_ENV_NAME
i get this: how to solve this problem
ResolvePackageNotFound:
  - libedit=3.1.20191231
  - xgboost=0.90
  - libcxx=10.0.0
  - ncurses=6.2
  - readline=8.0
  - libgfortran

**Comment by Bassel-kh** [comment]
i used this env yml for me:

**Comment by jenniferfedor** [comment]
Hi @Bassel-kh, thank you for using RAPIDS and for reporting this issue and your solution! One of our interns has been looking into this and was able to reproduce the issue on a machine running Windows 11 (unfortunately our team does not currently have a machine with Windows 10 available to us). Our intern was also able to restore the Python virtual environment by updating the environment.yml file as you describe. However, with this updated environment, some of our [tests](https://www.rapids.science/1.9/developers/test-cases/) fail and thus the results RAPIDS produces under these conditions are likely to be different than expected. We wanted to make sure you were aware of this. 

As we mention in our [documentation](https://www.rapids.science/1.9/setup/installation/), RAPIDS does not officially support native installation on Windows, so in light of this and other potential issues, **we highly recommend that you instead run RAPIDS through WSL or our Docker container** if either of those options are available to you.
