### ISSUE TITLE
Deprecation Warning in GAR features

### ISSUE THREAD

**Issue by EchhitJoshi** [carissalow/rapids#26]
/Users/echhitjoshi/Downloads/MOSHI/moshi_aware_master-2/src/features/google_activity_recognition.py:64: FutureWarning: using a dict on a Series for aggregation
is deprecated and will be removed in a future version. Use                 named aggregation instead.

    >>> grouper.agg(name_1=func_1, name_2=func_2)

  finalDataset.index.names = ['local_date']

**Comment by Meng6** [comment]
aa1baaf948d54e16cd7296835826ced016711c8b
