### ISSUE TITLE
Compliance Report: Different bins

### ISSUE THREAD

**Issue by nleo575** [carissalow/rapids#27]
The bins (groups) on the heat maps are different between the overall and the individual sensors. 
The Overall compliance report has bins of 30 minutes, while the others all seem to have bins of 1 hour.

**Comment by Meng6** [comment]
The overall compliance heatmap has bins of 5 minutes. Read the bin_size for both overall compliance heatmap and individual heatmaps (for each sensor) from the config file, config["PHONE_VALID_SENSED_DAYS"]["BIN_SIZE"].
