### ISSUE TITLE
Add support for filtering data within two dates

### ISSUE THREAD

**Issue by JulioV** [carissalow/rapids#36]
Fourth line of participants files in `data/external/pXX` will have two dates separated by a comma. Only data between these two dates will be included in the analysis.

For the `download_participants` script/rule the default dates will be: date 1 (date of the record in `aware_device` table) date 2 (today's date). 6bbc916702c2fcc98afc547be783773c8bc4486e

In the `download_dataset` rule, we need to filter out all data outside the range. If the range is not valid include all data.

**Comment by Meng6** [comment]
579df6325f2177d5394e8046fbf6ca3286d00724
