### ISSUE TITLE
Correct for battery sensing bug

### ISSUE THREAD

**Issue by Meng6** [carissalow/rapids#4]
Old versions of aware for Android and iOS collected battery data on a set frequency instead of on a battery level change. When aware crashed or the phone was turned off, aware would not log a change on the battery status column therefore there are pairs of rows where the battery level has a drastic change.

Proposed fix separate charging or discharging cycles when two timestamps are more than 3 mins  apart, or when battery level changes more than 3% , when they have the same battery status.

**Comment by JulioV** [comment]
Fixed in 0.1
