### ISSUE TITLE
Resolve possible confusion - Change `segment` to `day_segment`

### ISSUE THREAD

**Issue by kaguillera** [carissalow/rapids#40]
In the  following list of expand directive there is a `segment` parameter which should be really `day_segment` to avoid confusion. Please check other possible occurs.  

https://github.com/carissalow/rapids/blob/765bb462636d5029a05f54d4c558487e3786b90b/Snakefile#L22

https://github.com/carissalow/rapids/blob/765bb462636d5029a05f54d4c558487e3786b90b/Snakefile#L27

https://github.com/carissalow/rapids/blob/765bb462636d5029a05f54d4c558487e3786b90b/Snakefile#L30

**Comment by JulioV** [comment]
0049c1c
