### ISSUE TITLE
Delete screen raw event metrics and add countepisode

### ISSUE THREAD

**Issue by JulioV** [carissalow/rapids#44]
In https://github.com/carissalow/rapids/blob/master/src/features/screen_metrics.py, delete `counton` and `countunlock` and `unlocksperminute` (delete depency on `screen_with_datetime.csv`)

Add a metric called `countepisode` and `episodepersensedminutes` (per episode type, so far we only have one type: `unlock`).

**Comment by Meng6** [comment]
85f4ec2ab6ea9964dbbf007d9f8b3217e6569469
