### ISSUE TITLE
local_date is ommited

### ISSUE THREAD

**Issue by kennedyopokuasare** [carissalow/rapids#47]
https://github.com/carissalow/rapids/blob/a2d1ef2818ae4cd696ea4960308933e245e5232e/src/features/location_barnett_metrics.R#L60

suggested fix metrics_to_include<-c("local_date",metrics_to_include) before line 60

**Comment by JulioV** [comment]
Thanks for reporting it Kennedy, this should be fixed in dba2664ae517fa412cb8f6666f5e3a9f9ec5e7e7
