### ISSUE TITLE
GAR episodes don't include walking 

### ISSUE THREAD

**Issue by JulioV** [carissalow/rapids#52]
Google's Activity Recognition API provides a "walking" [label](https://developers.google.com/android/reference/com/google/android/gms/location/DetectedActivity), however, we do not take into account to create mobile episodes [here](https://github.com/carissalow/rapids/blob/master/src/features/google_activity_recognition.py).

**Comment by Meng6** [comment]
3314040912dccf4f3debee3ade8f514282331900
