### ISSUE TITLE
Extraction of location episodes from Aware data

### ISSUE THREAD

**Issue by JulioV** [carissalow/rapids#66]
This is a preliminary list for new features in addition computed by Barnett et al.

At the moment @nikunjgoel95 is coding the following features based on [Doryab et al](https://arxiv.org/pdf/1812.10394.pdf):

- Location Variance (Sum of the variance in latitude and longitude coordinates)
- Log of location variance
- Total distance traveled
- Average speed
- Variance in speed 
- Circadian movement (Lomb-Scargle method)
- Number of significant places (Clustering over speed and determining whether it is static or moving
- Number of transitions between places
- Radius of Gyration
- Time spent at top 3 (most frequented) local and global clusters
- Percentage of time spent moving
- Percentage of time spent in insignificant or rarely visited locations
- Statistics related to the length of stay at clusters such as maximum, minimum, average and standard deviation
- Location Entropy
- Normalized location entropy

Another option is to follow on [Saeb et al](https://www.jmir.org/2015/7/e175/?ncid=txtlnkusaolp00000618#Methods):
- Location variance
- Entropy and normalized entropy (Barnett et al. already computes this but based on the pause/flight model and after data imputation)
- Circadian movement (how does it differ from [Canzian et al.](https://dl.acm.org/doi/abs/10.1145/2750858.2805845))
- Transition time (similar to pause probability)

**Comment by nikunjgoel95** [comment]
All these features are computed and working smoothly.

- Location Variance (Sum of the variance in latitude and longitude coordinates)
- Log of location variance
- Total distance traveled
- Average speed
- Variance in speed
- Circadian movement (Lomb-Scargle method)

For the other features, as mentioned in [Doryab et al](https://arxiv.org/pdf/1812.10394.pdf) they are using **LABEL** as a parameter. In our data from AAPECS, we are getting LABEL as NaN and the research paper doesn't define the way the calculate a label.

**Comment by sefyas** [comment]
issues in the original implementation 

**location_variance_log**
The variance is sometimes `0` even when the data frame has multiple rows. The branch to deal with `lvar == 0` is never taken. The function thus returns `log10(0)` (i.e. `-inf`)

**radius_of_gyration**
`lat_lon` variable is sometimes empty after noise removal resulting in a division by zero and the function returns `nan`.
Also, I think the current implementation is different from the definition in this document. It does not fully account for the time spent at a point; it only accounts for moments of transition to the point.

**Comment by JulioV** [comment]
For Doryab's location features based on clustering and extracted for day epochs. Do we want to cluster on the whole dataset and then extract features, or cluster just the data belonging to an epoch?

**Comment by JulioV** [comment]
Create a new issue to cluster by dataset or time segment https://github.com/carissalow/rapids/issues/105

**Comment by JulioV** [comment]
Solved.
