### ISSUE TITLE
Change and/or Standarize Time Based Feature Units

### ISSUE THREAD

**Issue by kaguillera** [carissalow/rapids#71]
This issue was created to request the evaluation the current sensor time based feature units that are currently calculate by RAPIDS. The [Sensor Time Based Feature Units.docx](https://github.com/carissalow/rapids/files/4794116/Sensor.Time.Based.Feature.Units.docx) document is a list of all of the current time based features and there units that calculated to help with the discussion and evaluation of possibly changing and/or standardize the time units.

**Comment by JulioV** [comment]
Senor | Feature | Documented    Unit | Actual    (coded) Unit
-- | -- | -- | --
SMS (messages) | timefirstsms | minutes | minutes
  | timelastsms | minutes | minutes
Calls | meanduration | seconds | seconds
  | sumduration | seconds | seconds
  | minduration | seconds | seconds
  | maxduration | seconds | seconds
  | stdduration | seconds | seconds
  | modeduration | seconds | seconds
  | timefirstcall | minutes | minutes
  | timelastcall | minutes | minutes
Accelerometer | sumexertionalactivityepisodes | minutes | minutes
  | longestexertionalactivityepisode | minutes | minutes
  | longestnonexertionalactivityepisode | minutes | minutes
Applications Foreground | timeoffirstuse | minutes | minutes
  | timeoflastuse | minutes | minutes
Battery | sumdurationdischarge | minutes | minutes
  | sumdurationcharge | minutes | minutes
  | avgconsumptionrate | episodes/minute | episodes/minute
  | maxconsumptionrate | episodes/minute | episodes/minute
Activity Recognition | sumstationary | minutes | minutes
  | summobile | minutes | minutes
  | sumvehicle | minutes | minutes
Location | hometime | minutes | minutes
  | avgflightdur | seconds | seconds
  | stdflightdur | seconds | seconds

**Comment by JulioV** [comment]
We are leaving the call duration features in seconds for now
