### ISSUE TITLE
Extraction of screen episodes from Aware data

### ISSUE THREAD

**Issue by JulioV** [carissalow/rapids#73]
**Screen episodes Android**

- Remove LOCK (2) events that come within 50 milliseconds after ON (1) or OFF (0) (all screen episodes should now finish with an OFF)
- Group consecutive rows until an OFF is found (a new group id is incremented after every OFF)
- Swap UNLOCK (3) events that happen within 800 milliseconds before ON events (this happens rarely)
- Remove episodes that start with ON events for consistency with iOS (all remaining episodes should begin with UNLOCK and end with OFF)

**Screen episodes iOS**

- Only keep consecutive rows with LOCK (2) and UNLOCK (3) events
- Group consecutive rows until a LOCK event is found (a new group id is incremented after every LOCK)
- All episodes should being with a UNLOCK and end with LOCK

**Comment by sefyas** [comment]
UW's current implementation

* of records with the same timestamp and different status keep the one with the highest priority where there priority is defined as _off > on > locked > unlocked_
* assuming records sorted ascendingly timestamp, interactions periods are defined as pairs of consecutive rows where the status of the row with the smaller timestamp is _unlocked_ and the status of the next row is either _locked_ or _off_
* interaction periods that are too short (less than `MIN_INTERACTION_SECONDS`) or too long (more than `MAX_INTERACTION_SECONDS`) are removed. This takes care of not so uncommon cases where the app is killed after an unlocked event. The next locked or off event can be the next time the app is up and running.

**Comment by JulioV** [comment]
Working on a new feature (time of last screen episode)  #75

**Comment by JulioV** [comment]
Implement MIN_INTERACTION_SECONDS and MAX_INTERACTION_SECONDS as parameters

**Comment by sefyas** [comment]
once the min and max interval considerations are implemented within RAPIDS, we'll compare the output of RAPIDS implementation and UW implementation. We will investigate further if there are differences.

**Comment by JulioV** [comment]
Intervals are implemented (5f77161), you can start the testing
