### ISSUE TITLE
When two locations records have the same timestamp, keep the one with the highest accuracy

### ISSUE THREAD

**Issue by sefyas** [carissalow/rapids#78]
The cleaning steps for location data at UW

- removal of latitude and longitude of zeor
- in case of multiple records with the same timestamp, the record with the highest accuracy is kept

**Comment by JulioV** [comment]
this part is done removal of latitude and longitude of zeor

**Comment by JulioV** [comment]
the accuracy filtering is now done in 32472461ec8556f4d07585ed370da513816c90dd
