### ISSUE TITLE
For timefirstconversation and timelastconversation the wrong local_minute is selected

### ISSUE THREAD

**Issue by kaguillera** [carissalow/rapids#89]
**Describe the bug**
Currently for `timelastconversation` the max value of each column (i.e. `double_convo_start`, `local_hour`, `local_minute` ) is individually select and then multiplies local_hour * 60 + local_minute. That is the max `local_minute` from that column and not the `local_minute` that is actually associate with the max timestamp (the timestamp of the last conversation) 

**To Reproduce**
For example: 

![image](https://user-images.githubusercontent.com/1266505/90062965-929ad280-dcb6-11ea-8abd-a41b2a02a300.png)

Given the data above the code to get `timelastconversation` picks local_hour = 17 and local_minute = 50. When it should pick local_minute = 18.

This also happens with `timefirstconversation` but in reverse (it picks the min of each individual column)

**Comment by JulioV** [comment]
Fixed in 622d299
