### ISSUE TITLE
Conversation features have blank values when groupby set is empy

### ISSUE THREAD

**Issue by kaguillera** [carissalow/rapids#91]
**Describe the bug**
the pipeline but it is returning blanks (not 0 or NA) for `countconversation`, `aveconversationduration`, `sdconversationduration`, `minconversationduration`, `timefirstconversation`, `timelastconversation` when `conversation_data[conversation_data["conv_duration"] > 0].groupby(['local_date'])` is an empty dataframe.

**To Reproduce**
The input data has no conversations for 2020-07-08 evening day_segment. 

**Expected behavior**
The above values should show 0 (zero) or 'NA' where applicable. (eg. `countconversation` should be 0 while `sdconversationduration` should be NA)

**Screenshots**
Output of the current code:
![image](https://user-images.githubusercontent.com/1266505/90534117-5a2c4600-e147-11ea-9e71-a9a82f101820.png)

![image](https://user-images.githubusercontent.com/1266505/90534030-408afe80-e147-11ea-971f-6ecc3f704e1a.png)

**Comment by nikunjgoel95** [comment]
The CSV file generates values as applicable.
