### ISSUE TITLE
Extraction of battery features from Aware data

### ISSUE THREAD

**Issue by Meng6** [carissalow/rapids#92]
#### Unify battery data for iOS client V1
We transform iOS (only iOS client V1 needs this step as V2 does it out-of-the-box) battery logs into Android's format. iOS stores battery status: 0=unknown, 1=unplugged, 2=charging, 3=full, as opposed to Android's event: 1=unknown, 2=charging, 3=discharging, 4=not charging, 5=full.

We follow this algorithm to convert iOS battery data:
- Convert battery status from 3 to 5 for full status
- Convert battery status from 1 (unplugged) to 3 (discharge)

#### Calculate battery episodes
- Only keep consecutive rows with charging (2) and discharging (3) events
- Put consecutive rows with the same battery status into the same group
- Calculate battery_level & timestamp differences between the first and the last row in each group respectively
- Discard rows with time difference <= 6 minutes to avoid including quick cycles

#### Extract battery features based on battery episodes
- Rows with battery_level difference > 0 are regarded as discharging episode
- Rows with battery_level difference <= 0 are regarded as charging episode
- Consumption rate is the ratio between battery_level difference and time difference for a discharging episode

We extract features for different day segments (epochs) from battery episodes: "countdischarge", "sumdurationdischarge", "countcharge", "sumdurationcharge", "avgconsumptionrate", "maxconsumptionrate".

**Comment by JulioV** [comment]
Moved to https://github.com/carissalow/rapids/discussions/119
