### ISSUE TITLE
Split energy features by voice and noise

### ISSUE THREAD

**Issue by JulioV** [carissalow/rapids#94]
Replace sum,avg, sd, min, max energy features by the same features but computed for rows labeled as noise and voice

New names should be similar to: `sumnoiseenergy` instead of `sumenergy`

**Comment by nikunjgoel95** [comment]
https://github.com/carissalow/rapids/commit/6a5470e338f22a22e64bf7697312174ddbca289b

**Comment by JulioV** [comment]
@kaguillera let's modify the tests accordingly, please.

**Comment by JulioV** [comment]
@nikunjgoel95 please update the docs for the new features too

**Comment by nikunjgoel95** [comment]
https://github.com/carissalow/rapids/commit/cbaf129494d98659d8c582845db46ab11db1a865

**Comment by nikunjgoel95** [comment]
> @nikunjgoel95 please update the docs for the new features too
https://github.com/carissalow/rapids/commit/cbaf129494d98659d8c582845db46ab11db1a865
