### ISSUE TITLE
Fails to get different phone_sensed_bins.csv & plots with different BIN_SIZE

### ISSUE THREAD

**Issue by Meng6** [carissalow/rapids#99]
**Describe the bug**
When `BIN_SIZE` parameter is modified, the rule for visualization section would not execute again automatically as the output path does not contain the `BIN_SIZE` argument.

**To Reproduce**
Change the value of `BIN_SIZE` in config.yaml and rerun `snakemake -j1`.

**Expected behavior**
- New `data/interim/pXX/phone_sensed_bins.csv` file should be generated.
- New figures under **reports** folder should be generated.

**Comment by JulioV** [comment]
This is not necessary anymore as any changes in the config.yaml will re run any dependent file
